SET foreign_key_checks = 0;
LOAD DATA INFILE  '<PATH>PostTags.csv' INTO TABLE `PostTags`
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ','
OPTIONALLY ENCLOSED BY '\"'
ESCAPED BY '\"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(PostId, TagId);
SET foreign_key_checks = 1;
